steps:
# 1. Build the container image for the backend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/grapple-backend:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  id: 'Build backend image'

# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/grapple-backend:$COMMIT_SHA']
  id: 'Push backend image'

# 3. Deploy container image to Cloud Run
- name: 'gcr.io/google-cloud-sdk/gcloud:slim' # Using a more stable image
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'grapple-backend' # This will be the name of your Cloud Run service
    - '--image=gcr.io/$PROJECT_ID/grapple-backend:$COMMIT_SHA'
    - '--region=us-central1' # You can change this to your preferred region
    - '--platform=managed'
    - '--allow-unauthenticated' # Allows public access to your API
  id: 'Deploy to Cloud Run'

# This lists the built image name for reference
images:
- 'gcr.io/$PROJECT_ID/grapple-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
